<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Title>ZiTools</Title>
    <Description>RimWorld mod</Description>
    <Company>MaxZiCode</Company>
    <Product>ZiTools</Product>
    <Copyright>Copyright ©  2025</Copyright>
    <AssemblyVersion>1.9.6.0</AssemblyVersion>
    <FileVersion>1.9.6.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.4409" />
    <PackageReference Include="Lib.Harmony" Version="2.3.6" ExcludeAssets="runtime" />
  </ItemGroup>

</Project>
